// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mQHxTmy72Vk51OwLBUmnNQnasUjaOHo',
    appId: '1:248292876466:web:a6c49aebce1bd7e97869ab',
    messagingSenderId: '248292876466',
    projectId: 'littlesteps-52095',
    authDomain: 'littlesteps-52095.firebaseapp.com',
    storageBucket: 'littlesteps-52095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlz8AIORvwdeDrBQvYd50_wJVWvfMJoZM',
    appId: '1:248292876466:android:bdb961733a38d1dd7869ab',
    messagingSenderId: '248292876466',
    projectId: 'littlesteps-52095',
    storageBucket: 'littlesteps-52095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpkZzjdG2lFgF1x_o7oJSImb51uPtzsg',
    appId: '1:248292876466:ios:85286e7c7209e22c7869ab',
    messagingSenderId: '248292876466',
    projectId: 'littlesteps-52095',
    storageBucket: 'littlesteps-52095.firebasestorage.app',
    iosBundleId: 'com.example.littlesteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLpkZzjdG2lFgF1x_o7oJSImb51uPtzsg',
    appId: '1:248292876466:ios:85286e7c7209e22c7869ab',
    messagingSenderId: '248292876466',
    projectId: 'littlesteps-52095',
    storageBucket: 'littlesteps-52095.firebasestorage.app',
    iosBundleId: 'com.example.littlesteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6mQHxTmy72Vk51OwLBUmnNQnasUjaOHo',
    appId: '1:248292876466:web:e972e5e57ac2abed7869ab',
    messagingSenderId: '248292876466',
    projectId: 'littlesteps-52095',
    authDomain: 'littlesteps-52095.firebaseapp.com',
    storageBucket: 'littlesteps-52095.firebasestorage.app',
  );

}